### ISSUE TITLE
Spawn particles on enemy death

### ISSUE THREAD

**Issue by SorraTheOrc** [TheWizardsCode/PlaygroundDecember23#1]
When the enemy dies they just disappear. We should create some kind of explosive particle system.

**Comment by SorraTheOrc** [comment]
When the enemy dies they just disappear. We should create some kind of explosive particle system.

**Comment by bsimser** [comment]
As an enhancement maybe a specific particle effect for different types of enemies.

**Comment by SorraTheOrc** [comment]
- [ ] Add a death particle effect to the EnemyController
- [ ] Play the particles on death
- [ ] Add an audio effect to be played on death
- [ ] Trigger the audio
- [ ]
