### ISSUE TITLE
Between level hub

### ISSUE THREAD

**Issue by SorraTheOrc** [TheWizardsCode/PlaygroundDecember23#10]
Need feedback on game over and level complete - looks identical right now
Need a way to choose powerups for character

**Comment by YondernautsGames** [comment]
Have modified victory and death events to show separate popups and then load hub after a delay (can change delay in the game mode). The example hub scene shows how to modify persistent roguelike data, which is then picked up by the character movement upgrade system when in game. No specific upgrades have been applied - it's just a demo of the workflow
