### ISSUE TITLE
Character movement stats class

### ISSUE THREAD

**Issue by SorraTheOrc** [TheWizardsCode/PlaygroundDecember23#17]
Having this would allow character upgrades as these are used to manage movement upgrades (major and minor) and talk to the motion graph

**Comment by YondernautsGames** [comment]
Added MovementUpgradeSystem component to character prefab. Can modify various movement related properties (eg enabling jetpacks or modifying move speed) in there. Data modifiers (eg move speed) also use persistent rogue-lite data. Can tweak move speed from hub scene example and see effect in game.
