### ISSUE TITLE
Add Guns to some enemies

### ISSUE THREAD

**Issue by SorraTheOrc** [TheWizardsCode/PlaygroundDecember23#45]

**Comment by SorraTheOrc** [comment]
Lets make the saucers (to start) shoot the player. A simple raycast laser should be enough.

**Comment by YondernautsGames** [comment]
If you copy the new EnemyBurstFireGun (used on the caltrops) you could use that as a basis. An idea would be to swap the trigger for a semi auto one, tweak the script to make aiming at the player an option. Turn that off for the new gun, and point it z up, then swap the projectile prefab on the shooter module for a drunken player tracker and ammo effect for explosive. If you haven't found a solution you like by tomorrow then I'll look at that
